/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'inverse-on-surface': '#313031',
        'secondary': '#bcc7de',
        'inverse-primary': '#124af0',
        'on-primary-fixed': '#001356',
        'on-tertiary': '#690003',
        'surface-container-lowest': '#0e0e0f',
        'surface-container-high': '#2a2a2b',
        'primary': '#b8c3ff',
        'surface-dim': '#131314',
        'surface-bright': '#3a393a',
        'on-tertiary-container': '#ffece9',
        'outline-variant': '#434656',
        'on-error-container': '#ffdad6',
        'outline': '#8e90a2',
        'tertiary': '#ffb4aa',
        'on-surface': '#e5e2e3',
        'background': '#131314',
        'on-primary': '#002388',
        'inverse-surface': '#e5e2e3',
        'primary-container': '#2e5bff',
        'on-secondary-container': '#aeb9d0',
        'surface-variant': '#353436',
        'surface-container': '#201f20',
        'secondary-container': '#3e495d',
        'tertiary-container': '#d71a18',
        'on-primary-container': '#efefff',
        'surface-container-highest': '#353436',
        'on-surface-variant': '#c4c5d9',
        'primary-fixed': '#dde1ff',
        'surface-container-low': '#1c1b1c',
        'surface': '#131314',
        'on-background': '#e5e2e3',
        'error': '#ffb4ab',
        'primary-fixed-dim': '#b8c3ff',
        'surface-tint': '#b8c3ff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
